---

- name: Ensure OpenSSl and libssl are the latest versions
  apt: name={{ item }} update_cache={{ system.apt_update_cache }} state=latest
  with_items:
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install base packages
  apt: name={{ item }} update_cache={{ system.apt_update_cache }} force=yes state=installed
  with_items:
    - build-essential
    - htop
    - mercurial
    - git
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
  tags: packages

- name: Install base libraries
  apt: name={{ item }} update_cache={{ system.apt_update_cache }} force=yes state=installed
  with_items:
    - libjpeg-dev
    - libfreetype6-dev
    - zlib1g-dev
    - libpq-dev
  tags: packages