# -*- mode: ruby -*-

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
sudo apt-get update
sudo apt-get install -yq fabric python-jinja2 postgresql
sudo -u postgres psql -c"CREATE DATABASE bviewer;"
sudo -u postgres psql -c"CREATE ROLE bviewer LOGIN;"
sudo -u postgres psql -c"GRANT ALL privileges ON DATABASE bviewer TO bviewer;"
cd /provision
fab -H vagrant@localhost -p vagrant --set env=vagrant deploy_vagrant
cp -R /share/* /home/bviewer/share
chmod -R 777 /home/bviewer/share
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "ubuntu/trusty32"

    config.vm.network :private_network, ip: "4.4.4.4"
    config.vm.network "public_network"

    config.vm.provider :virtualbox do |vb|
     vb.name = "bviewer"
     vb.memory = 512
    end

    config.vm.synced_folder "../", "/provision"
    config.vm.synced_folder "../resources", "/share"
    config.vm.provision "shell", inline: $script

end
