# -*- mode: ruby -*-

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty32"

  config.vm.network :private_network, ip: "4.4.4.4"
  config.vm.network "public_network"

  config.vm.provider :virtualbox do |vb|
     vb.name = "bviewer"
     vb.memory = 512
  end
end
