# -*- mode: ruby -*-

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
sudo apt-get install -yq fabric python-jinja2 postgresql
sudo -u postgres psql -c"CREATE DATABASE bviewer;"
sudo -u postgres psql -c"CREATE ROLE bviewer LOGIN;"
sudo -u postgres psql -c"GRANT ALL privileges ON DATABASE bviewer TO bviewer;"
cd /provision
fab -H vagrant@localhost -p vagrant --set env=vagrant deploy
ln -s /share/* /home/bviewer/share
sudo -u bviewer psql <<EOF
BEGIN;
INSERT INTO auth_user VALUES (1, 'pbkdf2_sha256\\$12000\\$LykwxSKZcQbI\\$8UxDzt98Rq591Ucjg/suEzteFE64bph7vcadum4B5bg=', now(), true, 'admin', '', '', 'admin@bv.loc', true, true, now());
INSERT INTO auth_user VALUES (2, 'pbkdf2_sha256\\$12000\\$LykwxSKZcQbI\\$8UxDzt98Rq591Ucjg/suEzteFE64bph7vcadum4B5bg=', now(), false, 'demo', '', '', 'demo@bv.loc', false, true, now());
INSERT INTO core_gallery VALUES (1, 2, 'Demo gallery', '4.4.4.4', '', 32, 256, 'f4333db0', 'Demo gallery', 'Demo preview of bviewer gallery!');
INSERT INTO core_album VALUES ('f4333db0', NULL, 'Welcome', 1, 1, 1, true, 'Edit main album to change it', NULL, now());
COMMIT;
EOF
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "ubuntu/trusty32"

    config.vm.network :private_network, ip: "4.4.4.4"
    config.vm.network "public_network"

    config.vm.provider :virtualbox do |vb|
     vb.name = "bviewer"
     vb.memory = 512
    end

    config.vm.synced_folder "../", "/provision"
    config.vm.synced_folder "../resources", "/share"
    config.vm.provision "shell", inline: $script

end
