# -*- mode: ruby -*-

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "trusty32"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/trusty-server-cloudimg-i386-juju-vagrant-disk1.box"

  # config.vm.network :private_network, ip: "4.4.4.4"
  config.vm.network "public_network"

  config.vm.synced_folder "../resources", "/media/resources/"

  config.vm.provider :virtualbox do |vb|
     vb.name = "bviewer"
     vb.memory = 512
  end
end
